spring.application.name=Banking-Backend-API
# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db
spring.datasource.username=bank_user
spring.datasource.password=bank_pass

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server port (optional)
server.port=8080

#log file location
logging.file.name=logs/banking-app.log

#Log level
logging.level.root=INFO
logging.level.com.example=DEBUG
